comment:
    layout: diff, flags, files
    behavior: once
    require_base: no
    
codecov:
    require_ci_to_pass: no    
    
coverage:
    status:
        project:
            default:
                target: auto
        patch:
            default:
                target: auto
